### PR TITLE
Fixed typo, improved wordings, added effects

### LINKED ISSUE #1: [BUG] : Typos, need appropriate wordings for webpage

### PR DESCRIPTION
**Pull request by Kr555Dev**
Closes #1

- Fixed and `improved some wordings` to add more meaning while entering.
- Added `placeholders `for the boxes for user to understand better what to input without any confusion. 
- Also added appropriate `margin and padding` between the fields to make the webpage look clean and nice. 
- Added a` linear color gradient` to further enhance the looks and aesthetics of the webpage. 
- Added a snowfall effect using `css animation` and wrote the js code for the working.

### CODE REVIEW

**Comment by SnehaDeshmukh28** [comment]
Attach a Screenshot of the webpage having your edits

**Comment by SnehaDeshmukh28** [comment]
Remove the Gradient and keep it Plain

**Comment by Kr555Dev** [comment]
@SnehaDeshmukh28 I have removed the gradient.

**Comment by Kr555Dev** [comment]
Hii @SnehaDeshmukh28 
Can you please add the `hacktoberfest` topic to your repository, or you can add a `hacktoberfest-accepted` label to my PR/MR for my contribution to be counted for Hacktoberfest. 

Thank You!
image

**Comment by SnehaDeshmukh28** [comment]
Check

**Comment by Kr555Dev** [comment]
Yeah the pr has been counted and is under review. Thank you for your assistance

**Comment by SnehaDeshmukh28** [comment]
Glad to help!

**Pull request merged**
